"""update schema

Revision ID: 9031df1c46ac
Revises: 9f73c619b1dd
Create Date: 2026-05-21 05:39:55.478562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9031df1c46ac'
down_revision = '9f73c619b1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('date_paid',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_paid',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
